version: "3"
services:
  website:
    image: demo-nodejs
    ports:
      - "8080:80"
    restart: always

  degrees:
    image: degrees
    stdin_open: true  # Keep stdin open for the container
    tty: true
    ports:
      - "8087:8087"
    # networks:
    #   university:
    #     ipv4_address: 192.168.92.2

  students:
    image: students
    ports:
      - "8086:8086"
    # networks:
    #   university:
    #     ipv4_address: 192.168.92.3
volumes:
  degrees-data:
  students-data:
# networks:
#   university:
#     ipam:
#       driver: default
#       config:
#         - subnet: "192.168.92.0/24"
